on:
  pull_request:
    branches: [master, release]

jobs:
  build:
    name: "DevOps Challenge CI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: 1- Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 2- Install dependencies
        run: npm install

      - name: 4- Run tests
        run: npm run test

      - name: 5- Build application master ${{ github.event.pull_request.base.ref }} - by ${{ github.actor }}
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
        run: node index.js

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stazdx/devopschallenge:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}